// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eicsmwtzldydzdscvxtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpY3Ntd3R6bGR5ZHpkc2N2eHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMDgwMDQsImV4cCI6MjA2MDg4NDAwNH0._X5Ww7N7A53sBj-uDojPgIdGwgZ_fkygYOsti3mCRUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);